language: node_js
node_js:
  - 6
global:
  - NODE_ENV=production
install:
  - npm i mock
  - npm i chai
  - npm i jasmine
  - npm i mock-require
script: npm run test
before_script:
  - git clone $PRODUCTION_REPOSITORY build
  - eval `grep "^export " ./sh/env.sh`
branches:
  only:
  - master
before_deploy:
  - cd ./build
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: $HEROKU_APP
  run:
    - "npm install --production"
    - "npm run prod"