language: node_js
node_js:
  - 6
global:
  - NODE_ENV=production
install:
  - eval `grep "^export " ./sh/env.sh`
  - npm i mock
  - npm i chai
  - npm i jasmine
  - npm i mock-require
script: npm run test