language: node_js
node_js:
  - 6
global:
  - NODE_ENV=production
install:
  - npm i mock
  - npm i chai
  - npm i jasmine
  - npm i mock-require
script: npm run test
before_script:
  - git clone https://github.com/nedzelskiy/examples__deploy-complex-dev-boilerplate.git build
  - eval `grep "^export " ./sh/env.sh`
after_script:
  - echo DONE!