language: node_js
node_js:
  - 6
global:
  - NODE_ENV=production
install:
  - npm i mock
  - npm i chai
  - npm i jasmine
  - npm i mock-require
script: npm run test
before_script:
  - git clone https://github.com/nedzelskiy/examples__deploy-complex-dev-boilerplate.git build
  - eval `grep "^export " ./sh/env.sh`
branches:
  only:
  - master
before_deploy:
  - cd ./build
deploy:
  provider: heroku
  api_key: "178faff1-ef74-4810-8675-9b996f1964fc"
  skip_cleanup: true
  app: examples-dev-boilerplate
  on:
    repo: https://github.com/nedzelskiy/examples__deploy-complex-dev-boilerplate.git
    branch: master
  run:
    - "npm install --production"
    - "pm2 stop all"
    - "pm2 start server.js"